# Generated by Django 5.0.1 on 2024-02-02 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_equipment', models.CharField(max_length=60, verbose_name='оборудование')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='проблема')),
                ('status', models.CharField(choices=[('активная', 'Активная'), ('в процессе', 'В процессе'), ('выполнено', 'Выполнено')], default='активная', max_length=20)),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('type', models.CharField(choices=[('неожиданная проблема', 'Неожиданная проблема'), ('повторное обращение', 'Повторное обращение'), ('консультация', 'Kонсультация')], default='неожиданная проблема', max_length=40, verbose_name='Тип обращения')),
                ('priority', models.CharField(choices=[('низкий', 'Низкий'), ('средний', 'Средний'), ('высокий', 'Высокий')], default='cредний', max_length=40, verbose_name='Приоритет')),
                ('opened_date', models.DateTimeField(auto_now_add=True)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('equipment', models.ForeignKey(default='монитор', on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='helpdesk.equipment', verbose_name='оборудование')),
            ],
        ),
    ]
