# Generated by Django 5.0.1 on 2024-02-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_ticket_empl'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='photo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='files/%Y/%m/%d/', verbose_name='Файлы'),
        ),
    ]
