# Generated by Django 5.0.1 on 2024-02-06 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_ticket_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='photo',
            new_name='files',
        ),
    ]
