# Generated by Django 5.0.1 on 2024-02-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_uploadfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='files',
        ),
        migrations.AddField(
            model_name='ticket',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Файлы'),
        ),
    ]
