# Generated by Django 5.0.1 on 2024-02-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0008_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=50, verbose_name='проблема'),
        ),
    ]
