# Generated by Django 5.0.1 on 2024-02-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0009_alter_ticket_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Тема'),
        ),
    ]
