# Generated by Django 5.0.1 on 2024-02-15 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0010_alter_ticket_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='photo',
        ),
    ]
