# Generated by Django 5.0.1 on 2024-02-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0011_remove_ticket_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='выполнено'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='opened_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='открыто'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('активная', 'Активная'), ('в процессе', 'В процессе'), ('выполнено', 'Выполнено')], default='активная', max_length=20, verbose_name='статус'),
        ),
    ]
