# Generated by Django 5.0.1 on 2024-02-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cabinet',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='user',
            name='number_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
    ]
