# Generated by Django 5.0.1 on 2024-02-13 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_cabinet_user_number_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='post',
            field=models.CharField(blank=True, choices=[('администратор', 'Администратор'), ('бухгалтер', 'Бухгалтер'), ('директор', 'Директор'), ('секретарь', 'Секретарь'), ('продавец-консултант', 'Продавец-консультант')], max_length=50, null=True, verbose_name='должность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cabinet',
            field=models.IntegerField(blank=True, null=True, verbose_name='кабинет'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='номер телефона'),
        ),
        migrations.AddField(
            model_name='user',
            name='adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adresses', to='users.adresses', verbose_name='адрес'),
        ),
    ]
