# Generated by Django 5.0.1 on 2024-02-14 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuals',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Category', to='empl.category', verbose_name='Категории'),
        ),
    ]
