# Generated by Django 5.0.1 on 2024-02-14 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0002_alter_manuals_cat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manuals',
            options={'ordering': ['-time_create'], 'verbose_name': 'Рукводство', 'verbose_name_plural': 'Рукводства'},
        ),
        migrations.AlterField(
            model_name='manuals',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='empl.category', verbose_name='Категории'),
        ),
        migrations.AddIndex(
            model_name='manuals',
            index=models.Index(fields=['-time_create'], name='empl_manual_time_cr_ebe9b7_idx'),
        ),
    ]
