# Generated by Django 5.0.1 on 2024-02-17 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0003_alter_manuals_options_alter_manuals_cat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manuals',
            options={'ordering': ['-time_create'], 'verbose_name': 'статью', 'verbose_name_plural': 'статьи'},
        ),
    ]
